In [2]:
import pandas as pd
import numpy as np

In [4]:
CSV_PATH = './D001.csv'
df = pd.read_csv(CSV_PATH, encoding='cp949')

In [8]:
data = df.copy()
data

        연도   월       연월 수출입구분 수출입구분설명        물동량
0     2003   2  2003-02    OT    수출환적  161074.50
1     2003  11  2003-11    IT    수입환적  170733.50
2     2006   1  2006-01    OT    수출환적  203348.25
3     2018   1  2018-01    OO      수출  413797.75
4     2013   6  2013-06    OO      수출  389650.25
...    ...  ..      ...   ...     ...        ...
1371  1996   1  1996-01    OO      수출  158518.00
1372  2001   6  2001-06    OO      수출  215325.25
1373  2001   9  2001-09    OT    수출환적  127883.00
1374  2004   1  2004-01    IT    수입환적  181137.50
1375  2005   3  2005-03    OT    수출환적  221527.25

[1376 rows x 6 columns]

In [9]:
data = data.sort_values(["연도", "월"])
data

        연도  월       연월 수출입구분 수출입구분설명        물동량
602   1992  1  1992-01    OO      수출  104567.00
864   1992  1  1992-01    II      수입   92005.00
491   1992  2  1992-02    II      수입   91669.00
735   1992  2  1992-02    OO      수출  103903.00
282   1992  3  1992-03    OO      수출  137082.00
...    ... ..      ...   ...     ...        ...
1232  2025  1  2025-01    II      수입  468006.50
50    2025  2  2025-02    OO      수출  437906.75
207   2025  2  2025-02    OT    수출환적  599626.75
858   2025  2  2025-02    II      수입  392441.25
1156  2025  2  2025-02    IT    수입환적  533568.75

[1376 rows x 6 columns]

In [12]:
data["구조"] = data["수출입구분설명"].replace({
    "수입환적": "환적",
    "수출환적": "환적",
    "수입": "수출입",
    "수출": "수출입"
})
data

        연도  월       연월 수출입구분 수출입구분설명        물동량   구조
602   1992  1  1992-01    OO      수출  104567.00  수출입
864   1992  1  1992-01    II      수입   92005.00  수출입
491   1992  2  1992-02    II      수입   91669.00  수출입
735   1992  2  1992-02    OO      수출  103903.00  수출입
282   1992  3  1992-03    OO      수출  137082.00  수출입
...    ... ..      ...   ...     ...        ...  ...
1232  2025  1  2025-01    II      수입  468006.50  수출입
50    2025  2  2025-02    OO      수출  437906.75  수출입
207   2025  2  2025-02    OT    수출환적  599626.75   환적
858   2025  2  2025-02    II      수입  392441.25  수출입
1156  2025  2  2025-02    IT    수입환적  533568.75   환적

[1376 rows x 7 columns]

In [11]:
year_structure = (
    data.groupby(["연도", "구조"])["물동량"]
    .sum()
    .unstack()
    .reset_index()
)

year_structure

구조    연도          수출입           환적
0   1992   2635374.00          NaN
1   1993   2941235.00          NaN
2   1994   3582517.00          NaN
3   1995   4090333.75          NaN
4   1996   4362035.00          NaN
5   1997   4811161.50          NaN
6   1998   5311311.50          NaN
7   1999   5660882.00          NaN
8   2000   6382317.75          NaN
9   2001   5129694.00   2943107.75
10  2002   5566104.00   3887984.00
11  2003   6157128.25   4251414.25
12  2004   6698925.00   4791840.00
13  2005   6663670.75   5179724.00
14  2006   6830813.25   5208295.25
15  2007   7450248.75   5811591.00
16  2008   7644942.00   5808188.00
17  2009   6607973.75   5372636.25
18  2010   7917905.00   6276690.75
19  2011   8832312.00   7352641.75
20  2012   8898631.50   8147545.75
21  2013   8937645.50   8748453.00
22  2014   9253928.50   9429354.75
23  2015   9363406.25  10105318.25
24  2016   9620465.25   9835826.00
25  2017  10215068.25  10278407.00
26  2018  10233267.00  11429309.00
27  2019  10354104.75  11637895.50
28  2020   9803869.50  12020125.50
29  2021  10433457.25  12272672.50
30  2022  10312383.75  11765810.75
31  2023  10744745.25  12408762.75
32  2024  10904836.00  13497184.00
33  2025   1732784.00   2356844.25

In [19]:
# 전년 대비 환적 물동량 증가량
year_structure["환적증가량"] = (
    year_structure["환적"].diff()
)

year_structure

구조    연도          수출입           환적        환적증가량
0   1992   2635374.00          NaN          NaN
1   1993   2941235.00          NaN          NaN
2   1994   3582517.00          NaN          NaN
3   1995   4090333.75          NaN          NaN
4   1996   4362035.00          NaN          NaN
5   1997   4811161.50          NaN          NaN
6   1998   5311311.50          NaN          NaN
7   1999   5660882.00          NaN          NaN
8   2000   6382317.75          NaN          NaN
9   2001   5129694.00   2943107.75          NaN
10  2002   5566104.00   3887984.00    944876.25
11  2003   6157128.25   4251414.25    363430.25
12  2004   6698925.00   4791840.00    540425.75
13  2005   6663670.75   5179724.00    387884.00
14  2006   6830813.25   5208295.25     28571.25
15  2007   7450248.75   5811591.00    603295.75
16  2008   7644942.00   5808188.00     -3403.00
17  2009   6607973.75   5372636.25   -435551.75
18  2010   7917905.00   6276690.75    904054.50
19  2011   8832312.00   7352641.75   1075951.00
20  2012   8898631.50   8147545.75    794904.00
21  2013   8937645.50   8748453.00    600907.25
22  2014   9253928.50   9429354.75    680901.75
23  2015   9363406.25  10105318.25    675963.50
24  2016   9620465.25   9835826.00   -269492.25
25  2017  10215068.25  10278407.00    442581.00
26  2018  10233267.00  11429309.00   1150902.00
27  2019  10354104.75  11637895.50    208586.50
28  2020   9803869.50  12020125.50    382230.00
29  2021  10433457.25  12272672.50    252547.00
30  2022  10312383.75  11765810.75   -506861.75
31  2023  10744745.25  12408762.75    642952.00
32  2024  10904836.00  13497184.00   1088421.25
33  2025   1732784.00   2356844.25 -11140339.75

In [23]:
year_structure["환적기여도"] = (
    year_structure["환적증가량"] * 100
)

year_structure

구조    연도          수출입           환적        환적증가량         환적기여도
0   1992   2635374.00          NaN          NaN           NaN
1   1993   2941235.00          NaN          NaN           NaN
2   1994   3582517.00          NaN          NaN           NaN
3   1995   4090333.75          NaN          NaN           NaN
4   1996   4362035.00          NaN          NaN           NaN
5   1997   4811161.50          NaN          NaN           NaN
6   1998   5311311.50          NaN          NaN           NaN
7   1999   5660882.00          NaN          NaN           NaN
8   2000   6382317.75          NaN          NaN           NaN
9   2001   5129694.00   2943107.75          NaN           NaN
10  2002   5566104.00   3887984.00    944876.25  9.448762e+07
11  2003   6157128.25   4251414.25    363430.25  3.634302e+07
12  2004   6698925.00   4791840.00    540425.75  5.404258e+07
13  2005   6663670.75   5179724.00    387884.00  3.878840e+07
14  2006   6830813.25   5208295.25     28571.25  2.857125e+06
15  2007   7450248.75   5811591.00    603295.75  6.032958e+07
16  2008   7644942.00   5808188.00     -3403.00 -3.403000e+05
17  2009   6607973.75   5372636.25   -435551.75 -4.355518e+07
18  2010   7917905.00   6276690.75    904054.50  9.040545e+07
19  2011   8832312.00   7352641.75   1075951.00  1.075951e+08
20  2012   8898631.50   8147545.75    794904.00  7.949040e+07
21  2013   8937645.50   8748453.00    600907.25  6.009072e+07
22  2014   9253928.50   9429354.75    680901.75  6.809018e+07
23  2015   9363406.25  10105318.25    675963.50  6.759635e+07
24  2016   9620465.25   9835826.00   -269492.25 -2.694922e+07
25  2017  10215068.25  10278407.00    442581.00  4.425810e+07
26  2018  10233267.00  11429309.00   1150902.00  1.150902e+08
27  2019  10354104.75  11637895.50    208586.50  2.085865e+07
28  2020   9803869.50  12020125.50    382230.00  3.822300e+07
29  2021  10433457.25  12272672.50    252547.00  2.525470e+07
30  2022  10312383.75  11765810.75   -506861.75 -5.068618e+07
31  2023  10744745.25  12408762.75    642952.00  6.429520e+07
32  2024  10904836.00  13497184.00   1088421.25  1.088421e+08
33  2025   1732784.00   2356844.25 -11140339.75 -1.114034e+09